[package]
name = "pay-respects"
version = "0.4.7"
edition = "2021"

[dependencies]
colored = "2.0"
rule_parser = { path = "rule_parser" }
regex-lite = "0.1"

[profile.release]
strip = true
codegen-units = 1
lto = true
