command = "cd"

[[match_err]]
pattern = [
	"no such file or directory",
	"does not exist"
]
# as rust runs on its own environment, it's not possible to change
# the directory automatically
suggest = [
'''
mkdir -p {{command[1]}}
cd {{command[1]}} '''
]
